# Generated by Django 3.1.6 on 2021-03-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclingpointphoto',
            name='photo_url',
            field=models.ImageField(upload_to='media/recyclingpoint_pics/'),
        ),
    ]
