# Generated by Django 3.1.7 on 2021-04-07 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20210330_1750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecyclingPointPhotoToVet',
        ),
    ]
